language: node_js
node_js:
  - "0.11"
notifications:
  email:
    recipients:
      - raymon@raymonschouwenaar.nl
      - schouwenaar1988@gmail.com
    on_success: [change] # default: change
    on_failure: [always] # default: always
